language: node_js
node_js:
  - 'stable'
before_script:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: 'deploying'
